version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    command: bash -c /bin/bash
      
    stdin_open: true
    tty: true

volumes:
  gem_cache: